# Generated by Django 5.0.6 on 2024-07-09 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("nickname", models.CharField(max_length=50, verbose_name="user's nickname")),
                ("first_name", models.CharField(max_length=50, verbose_name="user's first name")),
                ("last_name", models.CharField(max_length=50, verbose_name="user's last name")),
                ("short_bio", models.CharField(blank=True, max_length=200, null=True, verbose_name="user's short bio")),
                ("date_of_birth", models.DateField(blank=True, null=True, verbose_name="user's date of birth")),
            ],
            options={
                "verbose_name": "profile",
                "verbose_name_plural": "profiles",
                "ordering": ["last_name"],
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
    ]
